export type Product = { slug: string; name: string; price: number; color: string; category: string; image: string; description: string; sizes: string[]; colors: string[] }

export const products: Product[] = [
  { slug: 'atelier-steel-watch', name: 'Atelier Steel Watch', price: 12990, color: 'Black / Steel', category: 'Watches', image: '/products/watch-01.png', description: 'A precise everyday watch with a brushed steel case, black dial, and considered leather strap.', sizes: ['OS'], colors: ['Black / Steel', 'Silver / Black'] },
  { slug: 'court-low-sneaker', name: 'Court Low Sneaker', price: 8990, color: 'Bone / Ink', category: 'Sneakers', image: '/products/sneaker-01.png', description: 'A clean low-top built with soft leather, a durable rubber sole, and an easy all-day profile.', sizes: ['7', '8', '9', '10', '11', '12'], colors: ['Bone / Ink', 'All Ink'] },
  { slug: 'frame-01-goggles', name: 'Frame 01 Goggles', price: 5490, color: 'Matte Black', category: 'Goggles', image: '/products/goggles-01.png', description: 'A streamlined wraparound frame with smoked lenses and a confident, light-catching finish.', sizes: ['OS'], colors: ['Matte Black', 'Smoke / Silver'] },
  { slug: 'heavyweight-tee', name: 'Heavyweight Tee', price: 3990, color: 'Ink', category: 'Essentials', image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=1200&q=85', description: 'A substantial everyday tee with a relaxed fit, clean neckline, and a finish that gets better with every wear.', sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'], colors: ['Ink', 'Bone', 'Moss'] },
  { slug: 'studio-tee', name: 'Studio Tee', price: 3490, color: 'Bone', category: 'Essentials', image: '/products/tee-02.png', description: 'A clean, structured tee cut from heavyweight cotton for quiet everyday polish.', sizes: ['S', 'M', 'L', 'XL'], colors: ['Bone', 'Ink'] },
  { slug: 'leather-card-wallet', name: 'Leather Card Wallet', price: 2990, color: 'Espresso', category: 'Accessories', image: '/products/wallet-01.png', description: 'A compact leather card wallet with a softly burnished finish and just enough room for the essentials.', sizes: ['OS'], colors: ['Espresso', 'Black'] },
  { slug: 'axis-bracelet', name: 'Axis Bracelet', price: 2490, color: 'Matte Black', category: 'Accessories', image: '/products/bracelet-01.png', description: 'A minimal metal bracelet designed to stack or stand alone.', sizes: ['OS'], colors: ['Matte Black'] },
  { slug: 'daily-cap', name: 'Daily Cap', price: 1990, color: 'Black', category: 'Accessories', image: '/products/cap-01.png', description: 'A structured six-panel cap with a clean profile and an easy everyday fit.', sizes: ['OS'], colors: ['Black', 'Stone'] },
  { slug: 'navy-chronograph', name: 'Navy Chronograph', price: 10990, color: 'Silver / Navy', category: 'Watches', image: '/products/watch-02.png', description: 'A precise chronograph with a cool steel case and deep navy dial.', sizes: ['OS'], colors: ['Silver / Navy'] },
  { slug: 'green-dial-watch', name: 'Green Dial Watch', price: 11990, color: 'Black / Green', category: 'Watches', image: '/products/watch-03.png', description: 'A dark, considered watch with a forest dial and brushed steel details.', sizes: ['OS'], colors: ['Black / Green'] },
  { slug: 'gold-dress-watch', name: 'Gold Dress Watch', price: 13990, color: 'Gold / Black', category: 'Watches', image: '/products/watch-04.png', description: 'A sharp gold-tone watch for evenings and everything after.', sizes: ['OS'], colors: ['Gold / Black'] },
  { slug: 'mesh-minimal-watch', name: 'Mesh Minimal Watch', price: 9990, color: 'Silver / White', category: 'Watches', image: '/products/watch-05.png', description: 'A clean silver watch with a white dial and mesh strap.', sizes: ['OS'], colors: ['Silver / White'] },
  { slug: 'city-frame', name: 'City Frame Goggles', price: 4490, color: 'Matte Black', category: 'Goggles', image: '/products/goggles-02.png', description: 'Angular smoke-lens frames for bright streets and late drives.', sizes: ['OS'], colors: ['Matte Black'] },
  { slug: 'amber-frame', name: 'Amber Frame Goggles', price: 4290, color: 'Tortoise / Amber', category: 'Goggles', image: '/products/goggles-03.png', description: 'A warm tortoiseshell frame with a confident, easy-wearing shape.', sizes: ['OS'], colors: ['Tortoise / Amber'] },
  { slug: 'aviator-blue', name: 'Aviator Blue Goggles', price: 4790, color: 'Silver / Blue', category: 'Goggles', image: '/products/goggles-04.png', description: 'Classic aviators with a sharp blue lens for bright days.', sizes: ['OS'], colors: ['Silver / Blue'] },
  { slug: 'velocity-wrap', name: 'Velocity Wrap Goggles', price: 4990, color: 'Black / Red', category: 'Goggles', image: '/products/goggles-05.png', description: 'A sporty wrap frame with a bold mirrored lens.', sizes: ['OS'], colors: ['Black / Red'] },
  { slug: 'cobalt-oversized-tee', name: 'Cobalt Oversized Tee', price: 3790, color: 'Cobalt', category: 'Essentials', image: '/products/tee-03.png', description: 'A relaxed heavyweight tee in a vivid cobalt blue.', sizes: ['S', 'M', 'L', 'XL'], colors: ['Cobalt', 'Black'] },
  { slug: 'court-blue-sneaker', name: 'Court Blue Sneaker', price: 9490, color: 'White / Cobalt', category: 'Sneakers', image: '/products/sneaker-02.png', description: 'A clean leather court sneaker with a sharp blue accent.', sizes: ['7', '8', '9', '10', '11'], colors: ['White / Cobalt'] },
  { slug: 'black-leather-belt', name: 'Black Leather Belt', price: 2790, color: 'Black / Silver', category: 'Accessories', image: '/products/belt-01.png', description: 'A refined leather belt with a low-key matte buckle.', sizes: ['30', '32', '34', '36', '38'], colors: ['Black / Silver'] },
  { slug: 'silver-chain', name: 'Silver Chain', price: 3290, color: 'Silver', category: 'Accessories', image: '/products/chain-01.png', description: 'A minimal silver chain that layers easily with every look.', sizes: ['OS'], colors: ['Silver'] },
]
export const getProduct = (slug: string) => products.find((product) => product.slug === slug)
export const money = (price: number) => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(price)
export const cartKey = 'brohood-cart'
export type CartLine = { slug: string; size: string; color: string; quantity: number }
export const getCart = (): CartLine[] => { if (typeof window === 'undefined') return []; try { return JSON.parse(localStorage.getItem(cartKey) || '[]') } catch { return [] } }
export const saveCart = (cart: CartLine[]) => localStorage.setItem(cartKey, JSON.stringify(cart))
export const cartCount = (cart: CartLine[]) => cart.reduce((sum, line) => sum + line.quantity, 0)
export const cartTotal = (cart: CartLine[]) => cart.reduce((sum, line) => { const product = getProduct(line.slug); return sum + (product?.price || 0) * line.quantity }, 0)
